### ISSUE TITLE
Using POSTMAN with OAuth against PROD?

### ISSUE THREAD

**Issue by jl0810** [plaid/plaid-postman#147]
sorry the docs seem to be lacking in this space.  I am using POSTMAN for limited personal use and it works fine for that purpose.  However 2 of my Banks are OAuth, so I got PROD access, approved OAuth from both institution -- now how do I get this to work using POSTMAN?   Could use an update to the README, please!

**Comment by jl0810** [comment]
Respectively it is not in there.  I just re read it.   If u believe it is would u mind citing the step number?

**Comment by jl0810** [comment]
Is that true? So for the link function i dont have to use a body tag for
URI?

**Comment by phoenixy1** [comment]
Hmm, I just tried it out and had no problem connecting my Bank of America account on prod using the instructions in the README. I would suggest checking out your OAuth registration status page and making sure that OAuth registration is complete for the institutions you're trying to connect: https://dashboard.plaid.com/team/oauth-institutions

**Comment by jl0810** [comment]
I did bofa too.  What happen when u try chase even if u dont havean
account.  Do u even get to a login screen

**Comment by jl0810** [comment]
Or Wells

Login screen doesn't even pop up

**Comment by phoenixy1** [comment]
In my case, I have no problem getting to the login screen for Wells Fargo. (My test account isn't approved for Chase OAuth, so that doesn't work for me, but that's expected.) It looks like this is likely to be a configuration or OAuth approval issue with your account and is not an issue with the Postman collection itself. Given that, I'm going to close this GitHub issue. If you need additional support, please go ahead and file a support ticket.

**Comment by jl0810** [comment]
not fully convinced that is accurate -- PLAID confirms my OAuth is fine.   are you from PLAID?   why is this so hard?

**Comment by jl0810** [comment]
again I have every single non OAuth provider working in prod, and dev 100% fine.  perfect, actually.
